// <auto-generated />
using System;
using Abernathy.Demographics.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Abernathy.Demographics.Service.Migrations
{
    [DbContext(typeof(DemographicsContext))]
    [Migration("20211017085205_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Abernathy.Demographics.Service.Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ZIPCode");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Abernathy.Demographics.Service.Models.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Female"
                        });
                });

            modelBuilder.Entity("Abernathy.Demographics.Service.Models.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 53,
                            DateOfBirth = new DateTime(1968, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lucas",
                            GenderId = 1,
                            LastName = "Ferguson"
                        },
                        new
                        {
                            Id = 2,
                            Age = 69,
                            DateOfBirth = new DateTime(1952, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pippa",
                            GenderId = 2,
                            LastName = "Rees"
                        },
                        new
                        {
                            Id = 3,
                            Age = 69,
                            DateOfBirth = new DateTime(1952, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Edward",
                            GenderId = 1,
                            LastName = "Arnold"
                        },
                        new
                        {
                            Id = 4,
                            Age = 75,
                            DateOfBirth = new DateTime(1946, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anthony",
                            GenderId = 1,
                            LastName = "Sharp"
                        },
                        new
                        {
                            Id = 5,
                            Age = 61,
                            DateOfBirth = new DateTime(1958, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Wendy",
                            GenderId = 2,
                            LastName = "Ince"
                        },
                        new
                        {
                            Id = 6,
                            Age = 72,
                            DateOfBirth = new DateTime(1949, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tracey",
                            GenderId = 2,
                            LastName = "Ross"
                        },
                        new
                        {
                            Id = 7,
                            Age = 55,
                            DateOfBirth = new DateTime(1966, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Claire",
                            GenderId = 2,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 8,
                            Age = 75,
                            DateOfBirth = new DateTime(1945, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Max",
                            GenderId = 1,
                            LastName = "Buckland"
                        },
                        new
                        {
                            Id = 9,
                            Age = 57,
                            DateOfBirth = new DateTime(1964, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Clark",
                            GenderId = 2,
                            LastName = "Natalie"
                        },
                        new
                        {
                            Id = 10,
                            Age = 61,
                            DateOfBirth = new DateTime(1959, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bailey",
                            GenderId = 1,
                            LastName = "Piers"
                        });
                });

            modelBuilder.Entity("Abernathy.Demographics.Service.Models.Entities.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhoneNumber");
                });

            modelBuilder.Entity("AddressPatient", b =>
                {
                    b.Property<int>("AddressesId")
                        .HasColumnType("int");

                    b.Property<int>("PatientsId")
                        .HasColumnType("int");

                    b.HasKey("AddressesId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("AddressPatient");
                });

            modelBuilder.Entity("PatientPhoneNumber", b =>
                {
                    b.Property<int>("PatientsId")
                        .HasColumnType("int");

                    b.Property<int>("PhoneNumbersId")
                        .HasColumnType("int");

                    b.HasKey("PatientsId", "PhoneNumbersId");

                    b.HasIndex("PhoneNumbersId");

                    b.ToTable("PatientPhoneNumber");
                });

            modelBuilder.Entity("Abernathy.Demographics.Service.Models.Entities.Patient", b =>
                {
                    b.HasOne("Abernathy.Demographics.Service.Models.Entities.Gender", "type")
                        .WithMany("Patients")
                        .HasForeignKey("GenderId")
                        .HasConstraintName("FK_Patient_Gender")
                        .IsRequired();

                    b.Navigation("type");
                });

            modelBuilder.Entity("AddressPatient", b =>
                {
                    b.HasOne("Abernathy.Demographics.Service.Models.Entities.Address", null)
                        .WithMany()
                        .HasForeignKey("AddressesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abernathy.Demographics.Service.Models.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientPhoneNumber", b =>
                {
                    b.HasOne("Abernathy.Demographics.Service.Models.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abernathy.Demographics.Service.Models.Entities.PhoneNumber", null)
                        .WithMany()
                        .HasForeignKey("PhoneNumbersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Abernathy.Demographics.Service.Models.Entities.Gender", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
